### PR TITLE
Add option for enabling `unsafe-eval`

### PR DESCRIPTION
**Pull request by jaylinski**
This option is often required when running webpack in development
mode, since it makes heavy use of `eval` in order to generate fast
source-maps.

See: https://webpack.js.org/configuration/devtool/

### CODE REVIEW

**Comment by jaylinski** [comment]
@lweichselbaum If you find some time, it would be nice to get this tagged and published somewhere in the near future. :pray:

**Comment by lweichselbaum** [comment]
Sorry forgot to close this. This should have been published as version 1.0.1 in https://www.npmjs.com/package/strict-csp

**Comment by jaylinski** [comment]
@lweichselbaum Thanks! Can you also publish the `strict-csp-html-webpack-plugin`-package? 🙏  (https://www.npmjs.com/package/strict-csp-html-webpack-plugin)

**Comment by lweichselbaum** [comment]
Done!

**Pull request merged**
